
config:

  prefix: " &8▸ &a&l✔ &8| &f"

  max-place-chest: 3

  sound:
    locked-chest: BLOCK_CHAIN_BREAK;1;1

  custom-chest:
    KEY_CHEST:
      id: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q4NzZmODJkNTNjNmIxM2Q4OGViMjFiZTMyMTE5ZjFhYWI2MzFkZGY2ZjZhZTlkNmJjMzc0MmVkMWRlYSJ9fX0="

      chest-key:
        id: TRIPWIRE_HOOK
        display_name: "&fKey Chest Key"
        lore:
          - "&8| &7Use this key to open a key chest."

      chest-item:
        id: PLAYER_HEAD
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q4NzZmODJkNTNjNmIxM2Q4OGViMjFiZTMyMTE5ZjFhYWI2MzFkZGY2ZjZhZTlkNmJjMzc0MmVkMWRlYSJ9fX0="
        display_name: "&fKey Chest"
        lore:
          - '&8| &7Place this chest     '
          - '&8| &7to get a key chest.  '

    PANEL_CHEST:
      id: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2UyZDc5NjEyMDIzZTI3MGJjODk1MzI3MjliYzcxMWY5YjhmZGUwY2VhY2RjNTljOTc5ZTFiNDM2MzM3NGYifX19"

      chest-item:
        id: PLAYER_HEAD
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2UyZDc5NjEyMDIzZTI3MGJjODk1MzI3MjliYzcxMWY5YjhmZGUwY2VhY2RjNTljOTc5ZTFiNDM2MzM3NGYifX19"
        display_name: "&fPanel Chest"
        lore:
          - '&8| &7Place this chest       '
          - '&8| &7to get a panel chest.  '