
config:

  prefix: " &8▸ &a&l✔ &8| &f"

  max-place-chest: 3
  max-friends: 4
  max-pin-length: 4


  damage-wrong-pin:
    enable: true
    damage: 3.0


  sound:
    locked-chest: BLOCK_CHAIN_BREAK;1;1
    max-digits: BLOCK_LEVER_CLICK;1;1.2
    add-digits: BLOCK_LEVER_CLICK;1;2
    reset-digits: BLOCK_LEVER_CLICK;1;1.4
    wrong-password: BLOCK_CHEST_LOCKED;1;1.8


  custom-chest:
    KEY_CHEST:
      id: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q4NzZmODJkNTNjNmIxM2Q4OGViMjFiZTMyMTE5ZjFhYWI2MzFkZGY2ZjZhZTlkNmJjMzc0MmVkMWRlYSJ9fX0="

      chest-key:
        id: TRIPWIRE_HOOK
        display_name: "&fKey Chest Key"
        lore:
          - "&8| &7Use this key to open a key chest."

      chest-item:
        id: PLAYER_HEAD
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q4NzZmODJkNTNjNmIxM2Q4OGViMjFiZTMyMTE5ZjFhYWI2MzFkZGY2ZjZhZTlkNmJjMzc0MmVkMWRlYSJ9fX0="
        display_name: "&fKey Chest"
        lore:
          - '&8| &7Place this chest     '
          - '&8| &7to get a key chest.  '

    FRIEND_CHEST:
      id: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGJjMmI1MmUwMzE5YjU0OTIzNjE3MzhlMDY0NDkzMDU2ZTQ3ZWI5NjMzNDYwNDY5ZmM4YWJlOWM2ODU0NmE4MSJ9fX0="

      chest-item:
        id: PLAYER_HEAD
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGJjMmI1MmUwMzE5YjU0OTIzNjE3MzhlMDY0NDkzMDU2ZTQ3ZWI5NjMzNDYwNDY5ZmM4YWJlOWM2ODU0NmE4MSJ9fX0="
        display_name: "&fFriend Chest"
        lore:
          - '&8| &7Place this chest     '
          - '&8| &7to set friends list.  '

    PANEL_CHEST:
      id: PLAYER_HEAD
      texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2UyZDc5NjEyMDIzZTI3MGJjODk1MzI3MjliYzcxMWY5YjhmZGUwY2VhY2RjNTljOTc5ZTFiNDM2MzM3NGYifX19"

      chest-item:
        id: PLAYER_HEAD
        texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2UyZDc5NjEyMDIzZTI3MGJjODk1MzI3MjliYzcxMWY5YjhmZGUwY2VhY2RjNTljOTc5ZTFiNDM2MzM3NGYifX19"
        display_name: "&fPanel Chest"
        lore:
          - '&8| &7Place this chest       '
          - '&8| &7to get a panel chest.  '

  inventory:
    friends-chest:
      title: "&8▸ Select Friends"
      size: 54

      friend-item:
        id: PLAYER_HEAD
        display_name: "&a&l✔ &8⋮ &f%player_name%"
        lore:
          - "&8| &7Click to remove this player."

      not-friend-item:
        id: PLAYER_HEAD
        display_name: "&c&l✘ &8⋮ &f%player_name%"
        lore:
          - "&8| &7Click to add this player."

      items:
        '1':
          id: PLAYER_HEAD
          slot: 50
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19"
          display_name: "#BABABANext"
          actions:
            - "[NEXT_PAGE]"
        '2':
          id: PLAYER_HEAD
          slot: 48
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ=="
          display_name: "#BABABAPrevious"
          actions:
            - "[PREVIOUS_PAGE]"
        '3':
          id: PLAYER_HEAD
          slot: 49
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc1NDgzNjJhMjRjMGZhODQ1M2U0ZDkzZTY4YzU5NjlkZGJkZTU3YmY2NjY2YzAzMTljMWVkMWU4NGQ4OTA2NSJ9fX0="
          display_name: "&cClose"
          actions:
            - "[CLOSE]"
        '4':
          id: GRAY_STAINED_GLASS_PANE
          slots:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 52
            - 53
            - 46
            - 45
        '5':
          id: LIGHT_GRAY_STAINED_GLASS_PANE
          slots:
            - 9
            - 17
            - 18
            - 27
            - 26
            - 35
            - 36
            - 44

    panel-chest:
      title: "&8▸ Enter your Password..."
      size: 45

      digits-display:
        id: NAME_TAG
        display_name: "&fCurrent Pin: %pin%"
        lore:
          - '&8KatsuChest'
          - ''
          - ' &8| &7 Enter your pin.'
          - ' &8| &7 in the panel.'
          - ''
          - "&e▸ Click to reset pin."
        actions:
          - '[RESET]'

      items:
        '2':
          id: PLAYER_HEAD
          slot: 34
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTc5YTVjOTVlZTE3YWJmZWY0NWM4ZGMyMjQxODk5NjQ5NDRkNTYwZjE5YTQ0ZjE5ZjhhNDZhZWYzZmVlNDc1NiJ9fX0="
          display_name: "&aConfirm Pin"
          lore:
            - '&8KatsuChest'
            - ''
            - ' &8| &7Make sure the '
            - ' &8| &7Pin is correct.'
            - ''
            - '&e▸ Click to confirm pin.'
          actions:
            - '[CONFIRM]'
        '3':
          id: PLAYER_HEAD
          slot: 32
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc1NDgzNjJhMjRjMGZhODQ1M2U0ZDkzZTY4YzU5NjlkZGJkZTU3YmY2NjY2YzAzMTljMWVkMWU4NGQ4OTA2NSJ9fX0="
          display_name: "&cClose Panel "
          actions:
            - '[CLOSE]'
        '4':
          id: PLAYER_HEAD
          slot: 10
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2E1MTZmYmFlMTYwNThmMjUxYWVmOWE2OGQzMDc4NTQ5ZjQ4ZjZkNWI2ODNmMTljZjVhMTc0NTIxN2Q3MmNjIn19fQ=="
          display_name: "#BABABA1"
          actions:
            - '[NUMBER]: 1'

        '5':
          id: PLAYER_HEAD
          slot: 11
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDY5OGFkZDM5Y2Y5ZTRlYTkyZDQyZmFkZWZkZWMzYmU4YTdkYWZhMTFmYjM1OWRlNzUyZTlmNTRhZWNlZGM5YSJ9fX0="
          display_name: "#BABABA2"
          actions:
            - '[NUMBER]: 2'

        '6':
          id: PLAYER_HEAD
          slot: 12
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmQ5ZTRjZDVlMWI5ZjNjOGQ2Y2E1YTFiZjQ1ZDg2ZWRkMWQ1MWU1MzVkYmY4NTVmZTlkMmY1ZDRjZmZjZDIifX19"
          display_name: "#BABABA3"
          actions:
            - '[NUMBER]: 3'

        '7':
          id: PLAYER_HEAD
          slot: 19
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjJhM2Q1Mzg5ODE0MWM1OGQ1YWNiY2ZjODc0NjlhODdkNDhjNWMxZmM4MmZiNGU3MmY3MDE1YTM2NDgwNTgifX19"
          display_name: "#BABABA4"
          actions:
            - '[NUMBER]: 4'

        '8':
          id: PLAYER_HEAD
          slot: 20
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDFmZTM2YzQxMDQyNDdjODdlYmZkMzU4YWU2Y2E3ODA5YjYxYWZmZDYyNDVmYTk4NDA2OTI3NWQxY2JhNzYzIn19fQ=="
          display_name: "#BABABA5"
          actions:
            - '[NUMBER]: 5'

        '9':
          id: PLAYER_HEAD
          slot: 21
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2FiNGRhMjM1OGI3YjBlODk4MGQwM2JkYjY0Mzk5ZWZiNDQxODc2M2FhZjg5YWZiMDQzNDUzNTYzN2YwYTEifX19"
          display_name: "#BABABA6"
          actions:
            - '[NUMBER]: 6'

        '10':
          id: PLAYER_HEAD
          slot: 28
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjk3NzEyYmEzMjQ5NmM5ZTgyYjIwY2M3ZDE2ZTE2OGIwMzViNmY4OWYzZGYwMTQzMjRlNGQ3YzM2NWRiM2ZiIn19fQ=="
          display_name: "#BABABA7"
          actions:
            - '[NUMBER]: 7'

        '11':
          id: PLAYER_HEAD
          slot: 29
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjk3NzEyYmEzMjQ5NmM5ZTgyYjIwY2M3ZDE2ZTE2OGIwMzViNmY4OWYzZGYwMTQzMjRlNGQ3YzM2NWRiM2ZiIn19fQ=="
          display_name: "#BABABA8"
          actions:
            - '[NUMBER]: 8'

        '12':
          id: PLAYER_HEAD
          slot: 30
          texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDZhYmM2MWRjYWVmYmQ1MmQ5Njg5YzA2OTdjMjRjN2VjNGJjMWFmYjU2YjhiMzc1NWU2MTU0YjI0YTVkOGJhIn19fQ=="
          display_name: "#BABABA9"
          actions:
            - '[NUMBER]: 9'

        '1':
          id: GRAY_STAINED_GLASS_PANE
          slots:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 13
            - 17
            - 18
            - 22
            - 23
            - 24
            - 25
            - 26
            - 27
            - 31
            - 35
            - 36
            - 37
            - 38
            - 39
            - 40
            - 41
            - 42
            - 43
            - 44

