name: KatsuChest
version: '${project.version}'
main: com.github.maazapan.katsuchest.KatsuChest
api-version: 1.16
softdepend:
  - MultiverseCore
  - WorldGuard
  - RedProtect
  - GriefPrevention
  - Towny
  - Lands
  - CoreProtect

commands:
  katsuchest:
    aliases:
      - ktchest
      - ktc
